#!/bin/bash
set -euo pipefail

# One-command background launcher for Phase 5.5 Cross V5-min training.
# Usage:
#   bash scripts/nohup_train_phase5_cross_v5.sh
#
# Optional env overrides are forwarded to train_phase5_cross_v5.sh, for example:
#   GPU_IDS=1,2,4 MAX_TRAIN_STEPS=500 bash scripts/nohup_train_phase5_cross_v5.sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
TRAIN_SCRIPT="${TRAIN_SCRIPT:-${SCRIPT_DIR}/train_phase5_cross_v5.sh}"

PROJECT_ROOT="${PROJECT_ROOT:-/home/lyw/wqx-DL/flow-edit/FlowEdit-main}"
CROSS_V5_OUTPUT_DIR="${CROSS_V5_OUTPUT_DIR:-/data/wqx/flowedit/controlnet_cross_v5_min}"
LOG_ROOT="${LOG_ROOT:-${CROSS_V5_OUTPUT_DIR}/nohup_logs}"
RUN_NAME="${RUN_NAME:-cross_v5_$(date +%Y%m%d_%H%M%S)}"
LOG_FILE="${LOG_FILE:-${LOG_ROOT}/${RUN_NAME}.log}"
PID_FILE="${PID_FILE:-${LOG_ROOT}/${RUN_NAME}.pid}"
MANIFEST_FILE="${MANIFEST_FILE:-${LOG_ROOT}/${RUN_NAME}.manifest.json}"

GPU_IDS="${GPU_IDS:-1,2,4}"
MAX_CUDA_MEMORY_GB="${MAX_CUDA_MEMORY_GB:-80}"
MAX_TRAIN_STEPS="${MAX_TRAIN_STEPS:-500}"
LR_WARMUP_STEPS="${LR_WARMUP_STEPS:-100}"
CHECKPOINTING_STEPS="${CHECKPOINTING_STEPS:-250}"
GRADIENT_CHECKPOINTING="${GRADIENT_CHECKPOINTING:-1}"

CROSS_V5_DENOISE_WEIGHT="${CROSS_V5_DENOISE_WEIGHT:-1.0}"
CROSS_V5_APPEARANCE_WEIGHT="${CROSS_V5_APPEARANCE_WEIGHT:-0.75}"
CROSS_V5_GEOMETRY_WEIGHT="${CROSS_V5_GEOMETRY_WEIGHT:-0.0}"
CROSS_V5_TEXTURE_WEIGHT="${CROSS_V5_TEXTURE_WEIGHT:-0.0}"
CROSS_V5_COLOR_WEIGHT="${CROSS_V5_COLOR_WEIGHT:-2.0}"
CROSS_V5_COLOR_SPACE="${CROSS_V5_COLOR_SPACE:-hed}"
CROSS_V5_VGG_WEIGHTS_PATH="${CROSS_V5_VGG_WEIGHTS_PATH:-}"
CROSS_V5_VGG_LAYERS="${CROSS_V5_VGG_LAYERS:-relu1_2,relu2_2,relu3_3}"
CROSS_V5_VGG_ALLOW_DOWNLOAD="${CROSS_V5_VGG_ALLOW_DOWNLOAD:-1}"
CROSS_V5_APPEARANCE_INTERVAL="${CROSS_V5_APPEARANCE_INTERVAL:-1}"
CROSS_V5_GEOMETRY_INTERVAL="${CROSS_V5_GEOMETRY_INTERVAL:-4}"
CROSS_V5_GEOMETRY_TIMESTEP_MAX="${CROSS_V5_GEOMETRY_TIMESTEP_MAX:-350.0}"
CROSS_V5_GEOMETRY_PREDICTOR_CHECKPOINT="${CROSS_V5_GEOMETRY_PREDICTOR_CHECKPOINT:-}"
CROSS_V5_GEOMETRY_PREDICTOR_DECODER="${CROSS_V5_GEOMETRY_PREDICTOR_DECODER:-mask2former}"
CROSS_V5_GEOMETRY_PREDICTOR_NUM_CLASSES="${CROSS_V5_GEOMETRY_PREDICTOR_NUM_CLASSES:-8}"
CROSS_V5_GEOMETRY_PREDICTOR_LOCAL_REPO="${CROSS_V5_GEOMETRY_PREDICTOR_LOCAL_REPO:-UNI-2h}"
CROSS_V5_GEOMETRY_PREDICTOR_MASK2FORMER_QUERIES="${CROSS_V5_GEOMETRY_PREDICTOR_MASK2FORMER_QUERIES:-100}"
CROSS_V5_GEOMETRY_PREDICTOR_IGNORE_INDEX="${CROSS_V5_GEOMETRY_PREDICTOR_IGNORE_INDEX:-255}"

CROSS_V5_PAIRING_SAMPLER="${CROSS_V5_PAIRING_SAMPLER:-1}"
CROSS_V5_PAIRS_PER_EPOCH="${CROSS_V5_PAIRS_PER_EPOCH:-}"
CROSS_V5_SAME_WSI_FRACTION="${CROSS_V5_SAME_WSI_FRACTION:-0.35}"
CROSS_V5_CROSS_WSI_FRACTION="${CROSS_V5_CROSS_WSI_FRACTION:-0.45}"
CROSS_V5_HIGH_APPEARANCE_GAP_FRACTION="${CROSS_V5_HIGH_APPEARANCE_GAP_FRACTION:-0.20}"
CROSS_V5_FULL_COVERAGE_FRACTION="${CROSS_V5_FULL_COVERAGE_FRACTION:-0.55}"
CROSS_V5_PARTIAL_COVERAGE_FRACTION="${CROSS_V5_PARTIAL_COVERAGE_FRACTION:-0.35}"
CROSS_V5_LOW_COVERAGE_FRACTION="${CROSS_V5_LOW_COVERAGE_FRACTION:-0.10}"
CROSS_V5_CLASS_BANK_DROPOUT_PROB="${CROSS_V5_CLASS_BANK_DROPOUT_PROB:-0.15}"
CROSS_V5_HIGH_GAP_QUANTILE="${CROSS_V5_HIGH_GAP_QUANTILE:-0.75}"
CROSS_V5_MIN_REF_PRESENCE_TOKENS="${CROSS_V5_MIN_REF_PRESENCE_TOKENS:-1.0}"
CROSS_V5_MIN_BANK_TOKEN_CONFIDENCE="${CROSS_V5_MIN_BANK_TOKEN_CONFIDENCE:-0.5}"

CROSS_V5_LOCAL_TOKENS_PER_CLASS="${CROSS_V5_LOCAL_TOKENS_PER_CLASS:-4}"
CROSS_V5_PROTOTYPE_SOURCE="${CROSS_V5_PROTOTYPE_SOURCE:-hed_stats}"
CROSS_V5_HED_CHANNELS="${CROSS_V5_HED_CHANNELS:-2}"
CROSS_V5_INCLUDE_HED_COVARIANCE="${CROSS_V5_INCLUDE_HED_COVARIANCE:-0}"
CROSS_V5_TEXTURE_STAT_KIND="${CROSS_V5_TEXTURE_STAT_KIND:-var}"
CROSS_V5_PRIOR_INIT_STD="${CROSS_V5_PRIOR_INIT_STD:-0.02}"

CROSS_V5_ADALN_DOUBLE_BLOCKS="${CROSS_V5_ADALN_DOUBLE_BLOCKS:-last}"
CROSS_V5_ADALN_HIDDEN_DIM="${CROSS_V5_ADALN_HIDDEN_DIM:-}"
CROSS_V5_INITIAL_GAMMA="${CROSS_V5_INITIAL_GAMMA:-0.05}"
CROSS_V5_ADALN_OUTPUT_INIT_STD="${CROSS_V5_ADALN_OUTPUT_INIT_STD:-0.02}"
CROSS_V5_DETACH_BANK="${CROSS_V5_DETACH_BANK:-0}"
CROSS_V5_MICRO_SMOKE="${CROSS_V5_MICRO_SMOKE:-0}"

SELF_RECONSTRUCTION_WARMUP_STEPS="${SELF_RECONSTRUCTION_WARMUP_STEPS:-0}"
SELF_RECONSTRUCTION_SAMPLE_PROB="${SELF_RECONSTRUCTION_SAMPLE_PROB:-0}"
REFERENCE_STYLE_LOSS_WEIGHT="${REFERENCE_STYLE_LOSS_WEIGHT:-0}"
REFERENCE_STYLE_LOSS_INTERVAL="${REFERENCE_STYLE_LOSS_INTERVAL:-0}"
REF_SWAP_LOSS_WEIGHT="${REF_SWAP_LOSS_WEIGHT:-0}"
REF_SWAP_LOSS_INTERVAL="${REF_SWAP_LOSS_INTERVAL:-0}"
REF_SWAP_VARIANTS="${REF_SWAP_VARIANTS:-}"
REF_CHECK_STEP="${REF_CHECK_STEP:-0}"

if [[ ! -f "${TRAIN_SCRIPT}" ]]; then
  echo "Missing train script: ${TRAIN_SCRIPT}" >&2
  exit 1
fi

mkdir -p "${LOG_ROOT}" "${CROSS_V5_OUTPUT_DIR}"

cat > "${MANIFEST_FILE}" <<EOF
{
  "run_name": "${RUN_NAME}",
  "repo_root": "${REPO_ROOT}",
  "project_root": "${PROJECT_ROOT}",
  "train_script": "${TRAIN_SCRIPT}",
  "output_dir": "${CROSS_V5_OUTPUT_DIR}",
  "log_file": "${LOG_FILE}",
  "pid_file": "${PID_FILE}",
  "gpu_ids": "${GPU_IDS}",
  "max_cuda_memory_gb": "${MAX_CUDA_MEMORY_GB}",
  "max_train_steps": "${MAX_TRAIN_STEPS}",
  "lr_warmup_steps": "${LR_WARMUP_STEPS}",
  "checkpointing_steps": "${CHECKPOINTING_STEPS}",
  "gradient_checkpointing": "${GRADIENT_CHECKPOINTING}",
  "cross_v5_denoise_weight": "${CROSS_V5_DENOISE_WEIGHT}",
  "cross_v5_appearance_weight": "${CROSS_V5_APPEARANCE_WEIGHT}",
  "cross_v5_geometry_weight": "${CROSS_V5_GEOMETRY_WEIGHT}",
  "cross_v5_texture_weight": "${CROSS_V5_TEXTURE_WEIGHT}",
  "cross_v5_color_weight": "${CROSS_V5_COLOR_WEIGHT}",
  "cross_v5_color_space": "${CROSS_V5_COLOR_SPACE}",
  "cross_v5_vgg_weights_path": "${CROSS_V5_VGG_WEIGHTS_PATH}",
  "cross_v5_vgg_layers": "${CROSS_V5_VGG_LAYERS}",
  "cross_v5_vgg_allow_download": "${CROSS_V5_VGG_ALLOW_DOWNLOAD}",
  "cross_v5_appearance_interval": "${CROSS_V5_APPEARANCE_INTERVAL}",
  "cross_v5_geometry_interval": "${CROSS_V5_GEOMETRY_INTERVAL}",
  "cross_v5_geometry_timestep_max": "${CROSS_V5_GEOMETRY_TIMESTEP_MAX}",
  "cross_v5_geometry_predictor_checkpoint": "${CROSS_V5_GEOMETRY_PREDICTOR_CHECKPOINT}",
  "cross_v5_geometry_predictor_decoder": "${CROSS_V5_GEOMETRY_PREDICTOR_DECODER}",
  "cross_v5_geometry_predictor_num_classes": "${CROSS_V5_GEOMETRY_PREDICTOR_NUM_CLASSES}",
  "cross_v5_geometry_predictor_local_repo": "${CROSS_V5_GEOMETRY_PREDICTOR_LOCAL_REPO}",
  "cross_v5_geometry_predictor_mask2former_queries": "${CROSS_V5_GEOMETRY_PREDICTOR_MASK2FORMER_QUERIES}",
  "cross_v5_geometry_predictor_ignore_index": "${CROSS_V5_GEOMETRY_PREDICTOR_IGNORE_INDEX}",
  "cross_v5_pairing_sampler": "${CROSS_V5_PAIRING_SAMPLER}",
  "cross_v5_pairs_per_epoch": "${CROSS_V5_PAIRS_PER_EPOCH}",
  "cross_v5_same_wsi_fraction": "${CROSS_V5_SAME_WSI_FRACTION}",
  "cross_v5_cross_wsi_fraction": "${CROSS_V5_CROSS_WSI_FRACTION}",
  "cross_v5_high_appearance_gap_fraction": "${CROSS_V5_HIGH_APPEARANCE_GAP_FRACTION}",
  "cross_v5_full_coverage_fraction": "${CROSS_V5_FULL_COVERAGE_FRACTION}",
  "cross_v5_partial_coverage_fraction": "${CROSS_V5_PARTIAL_COVERAGE_FRACTION}",
  "cross_v5_low_coverage_fraction": "${CROSS_V5_LOW_COVERAGE_FRACTION}",
  "cross_v5_class_bank_dropout_prob": "${CROSS_V5_CLASS_BANK_DROPOUT_PROB}",
  "cross_v5_high_gap_quantile": "${CROSS_V5_HIGH_GAP_QUANTILE}",
  "cross_v5_min_ref_presence_tokens": "${CROSS_V5_MIN_REF_PRESENCE_TOKENS}",
  "cross_v5_min_bank_token_confidence": "${CROSS_V5_MIN_BANK_TOKEN_CONFIDENCE}",
  "cross_v5_local_tokens_per_class": "${CROSS_V5_LOCAL_TOKENS_PER_CLASS}",
  "cross_v5_prototype_source": "${CROSS_V5_PROTOTYPE_SOURCE}",
  "cross_v5_hed_channels": "${CROSS_V5_HED_CHANNELS}",
  "cross_v5_include_hed_covariance": "${CROSS_V5_INCLUDE_HED_COVARIANCE}",
  "cross_v5_texture_stat_kind": "${CROSS_V5_TEXTURE_STAT_KIND}",
  "cross_v5_prior_init_std": "${CROSS_V5_PRIOR_INIT_STD}",
  "cross_v5_adaln_double_blocks": "${CROSS_V5_ADALN_DOUBLE_BLOCKS}",
  "cross_v5_adaln_hidden_dim": "${CROSS_V5_ADALN_HIDDEN_DIM}",
  "cross_v5_initial_gamma": "${CROSS_V5_INITIAL_GAMMA}",
  "cross_v5_adaln_output_init_std": "${CROSS_V5_ADALN_OUTPUT_INIT_STD}",
  "cross_v5_detach_bank": "${CROSS_V5_DETACH_BANK}",
  "cross_v5_micro_smoke": "${CROSS_V5_MICRO_SMOKE}",
  "self_reconstruction_warmup_steps": "${SELF_RECONSTRUCTION_WARMUP_STEPS}",
  "self_reconstruction_sample_prob": "${SELF_RECONSTRUCTION_SAMPLE_PROB}",
  "reference_style_loss_weight": "${REFERENCE_STYLE_LOSS_WEIGHT}",
  "reference_style_loss_interval": "${REFERENCE_STYLE_LOSS_INTERVAL}",
  "ref_swap_loss_weight": "${REF_SWAP_LOSS_WEIGHT}",
  "ref_swap_loss_interval": "${REF_SWAP_LOSS_INTERVAL}",
  "ref_swap_variants": "${REF_SWAP_VARIANTS}",
  "ref_check_step": "${REF_CHECK_STEP}",
  "started_at": "$(date -Is)"
}
EOF

export PROJECT_ROOT
export CROSS_V5_OUTPUT_DIR
export GPU_IDS
export MAX_CUDA_MEMORY_GB
export MAX_TRAIN_STEPS
export LR_WARMUP_STEPS
export CHECKPOINTING_STEPS
export GRADIENT_CHECKPOINTING
export CROSS_V5_DENOISE_WEIGHT
export CROSS_V5_APPEARANCE_WEIGHT
export CROSS_V5_GEOMETRY_WEIGHT
export CROSS_V5_TEXTURE_WEIGHT
export CROSS_V5_COLOR_WEIGHT
export CROSS_V5_COLOR_SPACE
export CROSS_V5_VGG_WEIGHTS_PATH
export CROSS_V5_VGG_LAYERS
export CROSS_V5_VGG_ALLOW_DOWNLOAD
export CROSS_V5_APPEARANCE_INTERVAL
export CROSS_V5_GEOMETRY_INTERVAL
export CROSS_V5_GEOMETRY_TIMESTEP_MAX
export CROSS_V5_GEOMETRY_PREDICTOR_CHECKPOINT
export CROSS_V5_GEOMETRY_PREDICTOR_DECODER
export CROSS_V5_GEOMETRY_PREDICTOR_NUM_CLASSES
export CROSS_V5_GEOMETRY_PREDICTOR_LOCAL_REPO
export CROSS_V5_GEOMETRY_PREDICTOR_MASK2FORMER_QUERIES
export CROSS_V5_GEOMETRY_PREDICTOR_IGNORE_INDEX
export CROSS_V5_PAIRING_SAMPLER
export CROSS_V5_PAIRS_PER_EPOCH
export CROSS_V5_SAME_WSI_FRACTION
export CROSS_V5_CROSS_WSI_FRACTION
export CROSS_V5_HIGH_APPEARANCE_GAP_FRACTION
export CROSS_V5_FULL_COVERAGE_FRACTION
export CROSS_V5_PARTIAL_COVERAGE_FRACTION
export CROSS_V5_LOW_COVERAGE_FRACTION
export CROSS_V5_CLASS_BANK_DROPOUT_PROB
export CROSS_V5_HIGH_GAP_QUANTILE
export CROSS_V5_MIN_REF_PRESENCE_TOKENS
export CROSS_V5_MIN_BANK_TOKEN_CONFIDENCE
export CROSS_V5_LOCAL_TOKENS_PER_CLASS
export CROSS_V5_PROTOTYPE_SOURCE
export CROSS_V5_HED_CHANNELS
export CROSS_V5_INCLUDE_HED_COVARIANCE
export CROSS_V5_TEXTURE_STAT_KIND
export CROSS_V5_PRIOR_INIT_STD
export CROSS_V5_ADALN_DOUBLE_BLOCKS
export CROSS_V5_ADALN_HIDDEN_DIM
export CROSS_V5_INITIAL_GAMMA
export CROSS_V5_ADALN_OUTPUT_INIT_STD
export CROSS_V5_DETACH_BANK
export CROSS_V5_MICRO_SMOKE
export SELF_RECONSTRUCTION_WARMUP_STEPS
export SELF_RECONSTRUCTION_SAMPLE_PROB
export REFERENCE_STYLE_LOSS_WEIGHT
export REFERENCE_STYLE_LOSS_INTERVAL
export REF_SWAP_LOSS_WEIGHT
export REF_SWAP_LOSS_INTERVAL
export REF_SWAP_VARIANTS
export REF_CHECK_STEP

nohup bash "${TRAIN_SCRIPT}" > "${LOG_FILE}" 2>&1 &
PID="$!"
echo "${PID}" > "${PID_FILE}"

echo "Started Cross V5-min training with nohup."
echo "PID: ${PID}"
echo "Log: ${LOG_FILE}"
echo "Manifest: ${MANIFEST_FILE}"
echo "Tail: tail -f ${LOG_FILE}"
