#!/bin/bash
set -euo pipefail

# Phase 5.5 Cross V5-min.
# Target geometry enters ControlNet. Reference appearance enters FLUX only through
# HED/texture bank driven SEAN-style spatial AdaLN modulation.

GPU_IDS="${GPU_IDS:-1,2,4}"
export CUDA_VISIBLE_DEVICES="${GPU_IDS}"
export NCCL_TIMEOUT="${NCCL_TIMEOUT:-3600}"
export NCCL_P2P_DISABLE="${NCCL_P2P_DISABLE:-0}"
export TORCH_NCCL_BLOCKING_WAIT="${TORCH_NCCL_BLOCKING_WAIT:-0}"
export TORCH_NCCL_ASYNC_ERROR_HANDLING="${TORCH_NCCL_ASYNC_ERROR_HANDLING:-1}"
export TOKENIZERS_PARALLELISM="${TOKENIZERS_PARALLELISM:-false}"
export HF_HOME="${HF_HOME:-/data/huggingface}"

PROJECT_ROOT="${PROJECT_ROOT:-/home/lyw/wqx-DL/flow-edit/FlowEdit-main}"
MODEL_DIR="${MODEL_DIR:-/data/huggingface/FLUX.1-dev}"
CROSS_META="${CROSS_META:-${PROJECT_ROOT}/phase5_runs/cross_meta/metadata_cross_train.json}"
CROSS_V5_OUTPUT_DIR="${CROSS_V5_OUTPUT_DIR:-/data/wqx/flowedit/controlnet_cross_v5_min}"

CONTROLNET_CHECKPOINT="${CONTROLNET_CHECKPOINT:-}"
CONDITIONING_CHECKPOINT="${CONDITIONING_CHECKPOINT:-}"
RESUME_FROM_CHECKPOINT="${RESUME_FROM_CHECKPOINT:-}"
LOAD_CONDITIONING_FROM_CHECKPOINT="${LOAD_CONDITIONING_FROM_CHECKPOINT:-0}"

PYTHON_BIN="${PYTHON_BIN:-python}"
MIXED_PRECISION="${MIXED_PRECISION:-bf16}"
IFS=',' read -r -a GPU_ID_ARRAY <<< "${GPU_IDS}"
NUM_PROCESSES="${NUM_PROCESSES:-${#GPU_ID_ARRAY[@]}}"
USE_8BIT_ADAM="${USE_8BIT_ADAM:-1}"
GRADIENT_CHECKPOINTING="${GRADIENT_CHECKPOINTING:-1}"
ENABLE_XFORMERS="${ENABLE_XFORMERS:-0}"
SET_GRADS_TO_NONE="${SET_GRADS_TO_NONE:-0}"

CONTROLNET_LEARNING_RATE="${CONTROLNET_LEARNING_RATE:-1e-6}"
CONTROLNET_TRAIN_MODE="${CONTROLNET_TRAIN_MODE:-outputs}"
CONTROLNET_TRAIN_X_EMBEDDER="${CONTROLNET_TRAIN_X_EMBEDDER:-1}"
CONDITIONING_LEARNING_RATE="${CONDITIONING_LEARNING_RATE:-5e-7}"

TARGET_TISSUE_ENCODING="${TARGET_TISSUE_ENCODING:-one_hot}"
TARGET_ONE_HOT_SCALE="${TARGET_ONE_HOT_SCALE:-4.0}"

SELF_RECONSTRUCTION_WARMUP_STEPS="${SELF_RECONSTRUCTION_WARMUP_STEPS:-0}"
SELF_RECONSTRUCTION_SAMPLE_PROB="${SELF_RECONSTRUCTION_SAMPLE_PROB:-0}"
REFERENCE_STYLE_LOSS_WEIGHT="${REFERENCE_STYLE_LOSS_WEIGHT:-0}"
REFERENCE_STYLE_LOSS_INTERVAL="${REFERENCE_STYLE_LOSS_INTERVAL:-0}"
REF_SWAP_LOSS_WEIGHT="${REF_SWAP_LOSS_WEIGHT:-0}"
REF_SWAP_LOSS_INTERVAL="${REF_SWAP_LOSS_INTERVAL:-0}"
REF_SWAP_VARIANTS="${REF_SWAP_VARIANTS:-}"
REF_CHECK_STEP="${REF_CHECK_STEP:-0}"

CROSS_V5_PAIRING_SAMPLER="${CROSS_V5_PAIRING_SAMPLER:-1}"
CROSS_V5_PAIRS_PER_EPOCH="${CROSS_V5_PAIRS_PER_EPOCH:-}"
CROSS_V5_SAME_WSI_FRACTION="${CROSS_V5_SAME_WSI_FRACTION:-0.35}"
CROSS_V5_CROSS_WSI_FRACTION="${CROSS_V5_CROSS_WSI_FRACTION:-0.45}"
CROSS_V5_HIGH_APPEARANCE_GAP_FRACTION="${CROSS_V5_HIGH_APPEARANCE_GAP_FRACTION:-0.20}"
CROSS_V5_FULL_COVERAGE_FRACTION="${CROSS_V5_FULL_COVERAGE_FRACTION:-0.55}"
CROSS_V5_PARTIAL_COVERAGE_FRACTION="${CROSS_V5_PARTIAL_COVERAGE_FRACTION:-0.35}"
CROSS_V5_LOW_COVERAGE_FRACTION="${CROSS_V5_LOW_COVERAGE_FRACTION:-0.10}"
CROSS_V5_CLASS_BANK_DROPOUT_PROB="${CROSS_V5_CLASS_BANK_DROPOUT_PROB:-0.15}"
CROSS_V5_HIGH_GAP_QUANTILE="${CROSS_V5_HIGH_GAP_QUANTILE:-0.75}"
CROSS_V5_MIN_REF_PRESENCE_TOKENS="${CROSS_V5_MIN_REF_PRESENCE_TOKENS:-1.0}"
CROSS_V5_MIN_BANK_TOKEN_CONFIDENCE="${CROSS_V5_MIN_BANK_TOKEN_CONFIDENCE:-0.5}"

CROSS_V5_LOCAL_TOKENS_PER_CLASS="${CROSS_V5_LOCAL_TOKENS_PER_CLASS:-4}"
CROSS_V5_PROTOTYPE_SOURCE="${CROSS_V5_PROTOTYPE_SOURCE:-hed_stats}"
CROSS_V5_HED_CHANNELS="${CROSS_V5_HED_CHANNELS:-2}"
CROSS_V5_INCLUDE_HED_COVARIANCE="${CROSS_V5_INCLUDE_HED_COVARIANCE:-0}"
CROSS_V5_TEXTURE_STAT_KIND="${CROSS_V5_TEXTURE_STAT_KIND:-var}"
CROSS_V5_PRIOR_INIT_STD="${CROSS_V5_PRIOR_INIT_STD:-0.02}"

CROSS_V5_ADALN_DOUBLE_BLOCKS="${CROSS_V5_ADALN_DOUBLE_BLOCKS:-last}"
CROSS_V5_ADALN_HIDDEN_DIM="${CROSS_V5_ADALN_HIDDEN_DIM:-}"
CROSS_V5_INITIAL_GAMMA="${CROSS_V5_INITIAL_GAMMA:-0.05}"
CROSS_V5_ADALN_OUTPUT_INIT_STD="${CROSS_V5_ADALN_OUTPUT_INIT_STD:-0.02}"
CROSS_V5_DETACH_BANK="${CROSS_V5_DETACH_BANK:-0}"

CROSS_V5_DENOISE_WEIGHT="${CROSS_V5_DENOISE_WEIGHT:-1.0}"
CROSS_V5_APPEARANCE_WEIGHT="${CROSS_V5_APPEARANCE_WEIGHT:-0.75}"
CROSS_V5_GEOMETRY_WEIGHT="${CROSS_V5_GEOMETRY_WEIGHT:-0.0}"
CROSS_V5_SWAP_SENSITIVITY_WEIGHT="${CROSS_V5_SWAP_SENSITIVITY_WEIGHT:-0.0}"
CROSS_V5_APPEARANCE_INTERVAL="${CROSS_V5_APPEARANCE_INTERVAL:-1}"
CROSS_V5_GEOMETRY_INTERVAL="${CROSS_V5_GEOMETRY_INTERVAL:-4}"
CROSS_V5_SMOKE_INTERVAL="${CROSS_V5_SMOKE_INTERVAL:-500}"
CROSS_V5_APPEARANCE_TIMESTEP_MIN="${CROSS_V5_APPEARANCE_TIMESTEP_MIN:-}"
CROSS_V5_APPEARANCE_TIMESTEP_MAX="${CROSS_V5_APPEARANCE_TIMESTEP_MAX:-}"
CROSS_V5_GEOMETRY_TIMESTEP_MIN="${CROSS_V5_GEOMETRY_TIMESTEP_MIN:-}"
CROSS_V5_GEOMETRY_TIMESTEP_MAX="${CROSS_V5_GEOMETRY_TIMESTEP_MAX:-350.0}"

CROSS_V5_COLOR_WEIGHT="${CROSS_V5_COLOR_WEIGHT:-2.0}"
CROSS_V5_TEXTURE_WEIGHT="${CROSS_V5_TEXTURE_WEIGHT:-0.0}"
CROSS_V5_COLOR_MEAN_WEIGHT="${CROSS_V5_COLOR_MEAN_WEIGHT:-1.0}"
CROSS_V5_COLOR_STD_WEIGHT="${CROSS_V5_COLOR_STD_WEIGHT:-1.0}"
CROSS_V5_COLOR_COVARIANCE_WEIGHT="${CROSS_V5_COLOR_COVARIANCE_WEIGHT:-0.0}"
CROSS_V5_APPEARANCE_MIN_PIXELS="${CROSS_V5_APPEARANCE_MIN_PIXELS:-32}"
CROSS_V5_COLOR_SPACE="${CROSS_V5_COLOR_SPACE:-hed}"
CROSS_V5_VGG_WEIGHTS_PATH="${CROSS_V5_VGG_WEIGHTS_PATH:-}"
CROSS_V5_VGG_LAYERS="${CROSS_V5_VGG_LAYERS:-relu1_2,relu2_2,relu3_3}"
CROSS_V5_VGG_ALLOW_DOWNLOAD="${CROSS_V5_VGG_ALLOW_DOWNLOAD:-1}"

CROSS_V5_GEOMETRY_PREDICTOR_CHECKPOINT="${CROSS_V5_GEOMETRY_PREDICTOR_CHECKPOINT:-}"
CROSS_V5_GEOMETRY_PREDICTOR_DECODER="${CROSS_V5_GEOMETRY_PREDICTOR_DECODER:-mask2former}"
CROSS_V5_GEOMETRY_PREDICTOR_NUM_CLASSES="${CROSS_V5_GEOMETRY_PREDICTOR_NUM_CLASSES:-8}"
CROSS_V5_GEOMETRY_PREDICTOR_LOCAL_REPO="${CROSS_V5_GEOMETRY_PREDICTOR_LOCAL_REPO:-UNI-2h}"
CROSS_V5_GEOMETRY_PREDICTOR_MASK2FORMER_QUERIES="${CROSS_V5_GEOMETRY_PREDICTOR_MASK2FORMER_QUERIES:-100}"
CROSS_V5_GEOMETRY_PREDICTOR_IGNORE_INDEX="${CROSS_V5_GEOMETRY_PREDICTOR_IGNORE_INDEX:-255}"

CROSS_V5_GEOMETRY_TISSUE_CE_WEIGHT="${CROSS_V5_GEOMETRY_TISSUE_CE_WEIGHT:-1.0}"
CROSS_V5_GEOMETRY_TISSUE_DICE_WEIGHT="${CROSS_V5_GEOMETRY_TISSUE_DICE_WEIGHT:-1.0}"
CROSS_V5_GEOMETRY_NUCLEI_CE_WEIGHT="${CROSS_V5_GEOMETRY_NUCLEI_CE_WEIGHT:-1.0}"
CROSS_V5_GEOMETRY_NUCLEI_DICE_WEIGHT="${CROSS_V5_GEOMETRY_NUCLEI_DICE_WEIGHT:-1.0}"
CROSS_V5_GEOMETRY_NUCLEI_BINARY_BCE_WEIGHT="${CROSS_V5_GEOMETRY_NUCLEI_BINARY_BCE_WEIGHT:-1.0}"
CROSS_V5_GEOMETRY_NUCLEI_BINARY_DICE_WEIGHT="${CROSS_V5_GEOMETRY_NUCLEI_BINARY_DICE_WEIGHT:-1.0}"
CROSS_V5_GEOMETRY_DENSE_L1_WEIGHT="${CROSS_V5_GEOMETRY_DENSE_L1_WEIGHT:-1.0}"

MAX_CUDA_MEMORY_GB="${MAX_CUDA_MEMORY_GB:-80}"
CUDA_MEMORY_CHECK_INTERVAL="${CUDA_MEMORY_CHECK_INTERVAL:-10}"
DATALOADER_NUM_WORKERS="${DATALOADER_NUM_WORKERS:-8}"
DATALOADER_PREFETCH_FACTOR="${DATALOADER_PREFETCH_FACTOR:-4}"
MAX_TRAIN_STEPS="${MAX_TRAIN_STEPS:-500}"
CHECKPOINTING_STEPS="${CHECKPOINTING_STEPS:-250}"
CHECKPOINTS_TOTAL_LIMIT="${CHECKPOINTS_TOTAL_LIMIT:-5}"
LR_WARMUP_STEPS="${LR_WARMUP_STEPS:-100}"
TRAIN_BATCH_SIZE="${TRAIN_BATCH_SIZE:-1}"
GRADIENT_ACCUMULATION_STEPS="${GRADIENT_ACCUMULATION_STEPS:-8}"
NUM_TRAIN_EPOCHS="${NUM_TRAIN_EPOCHS:-10}"
NUM_DOUBLE_LAYERS="${NUM_DOUBLE_LAYERS:-4}"
NUM_SINGLE_LAYERS="${NUM_SINGLE_LAYERS:-4}"
GUIDANCE_SCALE="${GUIDANCE_SCALE:-3.5}"
REPORT_TO="${REPORT_TO:-tensorboard}"
TRACKER_PROJECT_NAME="${TRACKER_PROJECT_NAME:-flux_controlnet_phase5_cross_v5_min}"
CROSS_V5_MICRO_SMOKE="${CROSS_V5_MICRO_SMOKE:-0}"

if [[ "${CROSS_V5_MICRO_SMOKE}" == "1" ]]; then
  MAX_TRAIN_STEPS=1
  GRADIENT_CHECKPOINTING=0
  CHECKPOINTING_STEPS=1000
  SELF_RECONSTRUCTION_WARMUP_STEPS=0
  SELF_RECONSTRUCTION_SAMPLE_PROB=0
  REFERENCE_STYLE_LOSS_WEIGHT=0
  REFERENCE_STYLE_LOSS_INTERVAL=0
  REF_SWAP_LOSS_WEIGHT=0
  REF_SWAP_LOSS_INTERVAL=0
  REF_SWAP_VARIANTS=""
  REF_CHECK_STEP=0
  CROSS_V5_APPEARANCE_INTERVAL=1
  CROSS_V5_GEOMETRY_WEIGHT=0
  CROSS_V5_GEOMETRY_INTERVAL=0
  CROSS_V5_SMOKE_INTERVAL=1
  CROSS_V5_TEXTURE_WEIGHT=0
fi

cd "${PROJECT_ROOT}"

TRAIN_OPTIMIZER_ARGS=()
if [[ "${USE_8BIT_ADAM}" == "1" ]]; then
  TRAIN_OPTIMIZER_ARGS+=(--use-8bit-adam)
fi

TRAIN_MEMORY_ARGS=()
if [[ "${GRADIENT_CHECKPOINTING}" == "1" ]]; then
  TRAIN_MEMORY_ARGS+=(--gradient-checkpointing)
fi
if [[ "${ENABLE_XFORMERS}" == "1" ]]; then
  TRAIN_MEMORY_ARGS+=(--enable-xformers-memory-efficient-attention)
fi
if [[ "${SET_GRADS_TO_NONE}" == "1" ]]; then
  TRAIN_MEMORY_ARGS+=(--set-grads-to-none)
fi

TRAIN_CONTROLNET_ARGS=(--controlnet-train-mode "${CONTROLNET_TRAIN_MODE}")
if [[ "${CONTROLNET_TRAIN_X_EMBEDDER}" == "1" ]]; then
  TRAIN_CONTROLNET_ARGS+=(--controlnet-train-x-embedder)
fi

TRAIN_CHECKPOINT_ARGS=()
if [[ -n "${CONTROLNET_CHECKPOINT}" ]]; then
  TRAIN_CHECKPOINT_ARGS+=(--controlnet_model_name_or_path "${CONTROLNET_CHECKPOINT}")
fi
if [[ -n "${CONDITIONING_CHECKPOINT}" ]]; then
  TRAIN_CHECKPOINT_ARGS+=(--conditioning-checkpoint "${CONDITIONING_CHECKPOINT}")
fi
if [[ "${LOAD_CONDITIONING_FROM_CHECKPOINT}" == "1" ]]; then
  TRAIN_CHECKPOINT_ARGS+=(--load-conditioning-from-checkpoint)
fi

RESUME_ARGS=()
if [[ -n "${RESUME_FROM_CHECKPOINT}" ]]; then
  RESUME_ARGS+=(--resume-from-checkpoint "${RESUME_FROM_CHECKPOINT}")
fi

TRAIN_CROSS_V5_PAIRING_ARGS=(
  --cross-v5-same-wsi-fraction "${CROSS_V5_SAME_WSI_FRACTION}"
  --cross-v5-cross-wsi-fraction "${CROSS_V5_CROSS_WSI_FRACTION}"
  --cross-v5-high-appearance-gap-fraction "${CROSS_V5_HIGH_APPEARANCE_GAP_FRACTION}"
  --cross-v5-full-coverage-fraction "${CROSS_V5_FULL_COVERAGE_FRACTION}"
  --cross-v5-partial-coverage-fraction "${CROSS_V5_PARTIAL_COVERAGE_FRACTION}"
  --cross-v5-low-coverage-fraction "${CROSS_V5_LOW_COVERAGE_FRACTION}"
  --cross-v5-class-bank-dropout-prob "${CROSS_V5_CLASS_BANK_DROPOUT_PROB}"
  --cross-v5-high-gap-quantile "${CROSS_V5_HIGH_GAP_QUANTILE}"
  --cross-v5-min-ref-presence-tokens "${CROSS_V5_MIN_REF_PRESENCE_TOKENS}"
  --cross-v5-min-bank-token-confidence "${CROSS_V5_MIN_BANK_TOKEN_CONFIDENCE}"
)
if [[ "${CROSS_V5_PAIRING_SAMPLER}" == "1" ]]; then
  TRAIN_CROSS_V5_PAIRING_ARGS+=(--cross-v5-pairing-sampler)
else
  TRAIN_CROSS_V5_PAIRING_ARGS+=(--no-cross-v5-pairing-sampler)
fi
if [[ -n "${CROSS_V5_PAIRS_PER_EPOCH}" ]]; then
  TRAIN_CROSS_V5_PAIRING_ARGS+=(--cross-v5-pairs-per-epoch "${CROSS_V5_PAIRS_PER_EPOCH}")
fi

TRAIN_CROSS_V5_BANK_ARGS=(
  --cross-v5-local-tokens-per-class "${CROSS_V5_LOCAL_TOKENS_PER_CLASS}"
  --cross-v5-prototype-source "${CROSS_V5_PROTOTYPE_SOURCE}"
  --cross-v5-hed-channels "${CROSS_V5_HED_CHANNELS}"
  --cross-v5-texture-stat-kind "${CROSS_V5_TEXTURE_STAT_KIND}"
  --cross-v5-prior-init-std "${CROSS_V5_PRIOR_INIT_STD}"
)
if [[ "${CROSS_V5_INCLUDE_HED_COVARIANCE}" == "1" ]]; then
  TRAIN_CROSS_V5_BANK_ARGS+=(--cross-v5-include-hed-covariance)
fi

TRAIN_CROSS_V5_ADALN_ARGS=(
  --cross-v5-adaln-double-blocks "${CROSS_V5_ADALN_DOUBLE_BLOCKS}"
  --cross-v5-initial-gamma "${CROSS_V5_INITIAL_GAMMA}"
  --cross-v5-adaln-output-init-std "${CROSS_V5_ADALN_OUTPUT_INIT_STD}"
)
if [[ -n "${CROSS_V5_ADALN_HIDDEN_DIM}" ]]; then
  TRAIN_CROSS_V5_ADALN_ARGS+=(--cross-v5-adaln-hidden-dim "${CROSS_V5_ADALN_HIDDEN_DIM}")
fi
if [[ "${CROSS_V5_DETACH_BANK}" == "1" ]]; then
  TRAIN_CROSS_V5_ADALN_ARGS+=(--cross-v5-detach-bank)
fi

TRAIN_CROSS_V5_TIMESTEP_ARGS=()
if [[ -n "${CROSS_V5_APPEARANCE_TIMESTEP_MIN}" ]]; then
  TRAIN_CROSS_V5_TIMESTEP_ARGS+=(--cross-v5-appearance-timestep-min "${CROSS_V5_APPEARANCE_TIMESTEP_MIN}")
fi
if [[ -n "${CROSS_V5_APPEARANCE_TIMESTEP_MAX}" ]]; then
  TRAIN_CROSS_V5_TIMESTEP_ARGS+=(--cross-v5-appearance-timestep-max "${CROSS_V5_APPEARANCE_TIMESTEP_MAX}")
fi
if [[ -n "${CROSS_V5_GEOMETRY_TIMESTEP_MIN}" ]]; then
  TRAIN_CROSS_V5_TIMESTEP_ARGS+=(--cross-v5-geometry-timestep-min "${CROSS_V5_GEOMETRY_TIMESTEP_MIN}")
fi
if [[ -n "${CROSS_V5_GEOMETRY_TIMESTEP_MAX}" ]]; then
  TRAIN_CROSS_V5_TIMESTEP_ARGS+=(--cross-v5-geometry-timestep-max "${CROSS_V5_GEOMETRY_TIMESTEP_MAX}")
fi

TRAIN_CROSS_V5_VGG_ARGS=(--cross-v5-vgg-layers "${CROSS_V5_VGG_LAYERS}")
if [[ -n "${CROSS_V5_VGG_WEIGHTS_PATH}" ]]; then
  TRAIN_CROSS_V5_VGG_ARGS+=(--cross-v5-vgg-weights-path "${CROSS_V5_VGG_WEIGHTS_PATH}")
fi
if [[ "${CROSS_V5_VGG_ALLOW_DOWNLOAD}" != "1" ]]; then
  TRAIN_CROSS_V5_VGG_ARGS+=(--cross-v5-no-vgg-download)
fi

TRAIN_CROSS_V5_GEOMETRY_PREDICTOR_ARGS=()
if [[ -n "${CROSS_V5_GEOMETRY_PREDICTOR_CHECKPOINT}" ]]; then
  TRAIN_CROSS_V5_GEOMETRY_PREDICTOR_ARGS+=(
    --cross-v5-geometry-predictor-checkpoint "${CROSS_V5_GEOMETRY_PREDICTOR_CHECKPOINT}"
    --cross-v5-geometry-predictor-decoder "${CROSS_V5_GEOMETRY_PREDICTOR_DECODER}"
    --cross-v5-geometry-predictor-num-classes "${CROSS_V5_GEOMETRY_PREDICTOR_NUM_CLASSES}"
    --cross-v5-geometry-predictor-local-repo "${CROSS_V5_GEOMETRY_PREDICTOR_LOCAL_REPO}"
    --cross-v5-geometry-predictor-mask2former-queries "${CROSS_V5_GEOMETRY_PREDICTOR_MASK2FORMER_QUERIES}"
    --cross-v5-geometry-predictor-ignore-index "${CROSS_V5_GEOMETRY_PREDICTOR_IGNORE_INDEX}"
  )
fi

echo "Cross V5 launch: gpus=${GPU_IDS} processes=${NUM_PROCESSES} max_steps=${MAX_TRAIN_STEPS} output=${CROSS_V5_OUTPUT_DIR}"
echo "Cross V5 losses: denoise=${CROSS_V5_DENOISE_WEIGHT} appearance=${CROSS_V5_APPEARANCE_WEIGHT} geometry=${CROSS_V5_GEOMETRY_WEIGHT} color=${CROSS_V5_COLOR_WEIGHT} texture=${CROSS_V5_TEXTURE_WEIGHT}"
echo "Cross V5 bank: prototype=${CROSS_V5_PROTOTYPE_SOURCE} local_tokens=${CROSS_V5_LOCAL_TOKENS_PER_CLASS} bank_dropout=${CROSS_V5_CLASS_BANK_DROPOUT_PROB} detach_bank=${CROSS_V5_DETACH_BANK}"
echo "Cross V5 AdaLN: double_blocks=${CROSS_V5_ADALN_DOUBLE_BLOCKS} initial_gamma=${CROSS_V5_INITIAL_GAMMA} output_init_std=${CROSS_V5_ADALN_OUTPUT_INIT_STD}"
echo "Cross V5 pairing: enabled=${CROSS_V5_PAIRING_SAMPLER} same=${CROSS_V5_SAME_WSI_FRACTION} cross=${CROSS_V5_CROSS_WSI_FRACTION} high_gap=${CROSS_V5_HIGH_APPEARANCE_GAP_FRACTION} coverage=${CROSS_V5_FULL_COVERAGE_FRACTION}/${CROSS_V5_PARTIAL_COVERAGE_FRACTION}/${CROSS_V5_LOW_COVERAGE_FRACTION}"
echo "Cross V5 VGG: layers=${CROSS_V5_VGG_LAYERS} weights_path=${CROSS_V5_VGG_WEIGHTS_PATH:-torchvision_default} allow_download=${CROSS_V5_VGG_ALLOW_DOWNLOAD}"
echo "Cross V5 geometry predictor: checkpoint=${CROSS_V5_GEOMETRY_PREDICTOR_CHECKPOINT:-none} decoder=${CROSS_V5_GEOMETRY_PREDICTOR_DECODER} local_repo=${CROSS_V5_GEOMETRY_PREDICTOR_LOCAL_REPO}"
echo "Cross V5 intervals: appearance=${CROSS_V5_APPEARANCE_INTERVAL} geometry=${CROSS_V5_GEOMETRY_INTERVAL} geometry_tmax=${CROSS_V5_GEOMETRY_TIMESTEP_MAX} memory_limit_gb=${MAX_CUDA_MEMORY_GB} micro_smoke=${CROSS_V5_MICRO_SMOKE}"

accelerate launch --multi_gpu --num_processes="${NUM_PROCESSES}" --gpu_ids="${GPU_IDS}" \
  controlnet_train/cli/train_controlnet_flux_cross_v5.py \
  --pretrained_model_name_or_path "${MODEL_DIR}" \
  --train-metadata "${CROSS_META}" \
  "${TRAIN_CHECKPOINT_ARGS[@]}" \
  --output-dir "${CROSS_V5_OUTPUT_DIR}" \
  "${RESUME_ARGS[@]}" \
  --logging-dir logs \
  --seed 42 \
  --train-batch-size "${TRAIN_BATCH_SIZE}" \
  --gradient-accumulation-steps "${GRADIENT_ACCUMULATION_STEPS}" \
  --num-train-epochs "${NUM_TRAIN_EPOCHS}" \
  --max-train-steps "${MAX_TRAIN_STEPS}" \
  --self-reconstruction-warmup-steps "${SELF_RECONSTRUCTION_WARMUP_STEPS}" \
  --self-reconstruction-sample-prob "${SELF_RECONSTRUCTION_SAMPLE_PROB}" \
  --reference-style-loss-weight "${REFERENCE_STYLE_LOSS_WEIGHT}" \
  --reference-style-loss-interval "${REFERENCE_STYLE_LOSS_INTERVAL}" \
  --ref-swap-loss-weight "${REF_SWAP_LOSS_WEIGHT}" \
  --ref-swap-loss-interval "${REF_SWAP_LOSS_INTERVAL}" \
  --ref-swap-variants "${REF_SWAP_VARIANTS}" \
  --ref-check-step "${REF_CHECK_STEP}" \
  --target-tissue-encoding "${TARGET_TISSUE_ENCODING}" \
  --target-one-hot-scale "${TARGET_ONE_HOT_SCALE}" \
  "${TRAIN_CROSS_V5_PAIRING_ARGS[@]}" \
  "${TRAIN_CROSS_V5_BANK_ARGS[@]}" \
  "${TRAIN_CROSS_V5_ADALN_ARGS[@]}" \
  --cross-v5-denoise-weight "${CROSS_V5_DENOISE_WEIGHT}" \
  --cross-v5-appearance-weight "${CROSS_V5_APPEARANCE_WEIGHT}" \
  --cross-v5-geometry-weight "${CROSS_V5_GEOMETRY_WEIGHT}" \
  --cross-v5-swap-sensitivity-weight "${CROSS_V5_SWAP_SENSITIVITY_WEIGHT}" \
  --cross-v5-appearance-interval "${CROSS_V5_APPEARANCE_INTERVAL}" \
  --cross-v5-geometry-interval "${CROSS_V5_GEOMETRY_INTERVAL}" \
  --cross-v5-smoke-interval "${CROSS_V5_SMOKE_INTERVAL}" \
  "${TRAIN_CROSS_V5_TIMESTEP_ARGS[@]}" \
  --cross-v5-color-weight "${CROSS_V5_COLOR_WEIGHT}" \
  --cross-v5-texture-weight "${CROSS_V5_TEXTURE_WEIGHT}" \
  --cross-v5-color-mean-weight "${CROSS_V5_COLOR_MEAN_WEIGHT}" \
  --cross-v5-color-std-weight "${CROSS_V5_COLOR_STD_WEIGHT}" \
  --cross-v5-color-covariance-weight "${CROSS_V5_COLOR_COVARIANCE_WEIGHT}" \
  --cross-v5-appearance-min-pixels "${CROSS_V5_APPEARANCE_MIN_PIXELS}" \
  --cross-v5-color-space "${CROSS_V5_COLOR_SPACE}" \
  "${TRAIN_CROSS_V5_VGG_ARGS[@]}" \
  "${TRAIN_CROSS_V5_GEOMETRY_PREDICTOR_ARGS[@]}" \
  --cross-v5-geometry-tissue-ce-weight "${CROSS_V5_GEOMETRY_TISSUE_CE_WEIGHT}" \
  --cross-v5-geometry-tissue-dice-weight "${CROSS_V5_GEOMETRY_TISSUE_DICE_WEIGHT}" \
  --cross-v5-geometry-nuclei-ce-weight "${CROSS_V5_GEOMETRY_NUCLEI_CE_WEIGHT}" \
  --cross-v5-geometry-nuclei-dice-weight "${CROSS_V5_GEOMETRY_NUCLEI_DICE_WEIGHT}" \
  --cross-v5-geometry-nuclei-binary-bce-weight "${CROSS_V5_GEOMETRY_NUCLEI_BINARY_BCE_WEIGHT}" \
  --cross-v5-geometry-nuclei-binary-dice-weight "${CROSS_V5_GEOMETRY_NUCLEI_BINARY_DICE_WEIGHT}" \
  --cross-v5-geometry-dense-l1-weight "${CROSS_V5_GEOMETRY_DENSE_L1_WEIGHT}" \
  --learning-rate "${CONTROLNET_LEARNING_RATE}" \
  "${TRAIN_CONTROLNET_ARGS[@]}" \
  --conditioning-learning-rate "${CONDITIONING_LEARNING_RATE}" \
  --lr-scheduler constant_with_warmup \
  --lr-warmup-steps "${LR_WARMUP_STEPS}" \
  --checkpointing-steps "${CHECKPOINTING_STEPS}" \
  --checkpoints-total-limit "${CHECKPOINTS_TOTAL_LIMIT}" \
  --mixed-precision "${MIXED_PRECISION}" \
  "${TRAIN_OPTIMIZER_ARGS[@]}" \
  "${TRAIN_MEMORY_ARGS[@]}" \
  --max-cuda-memory-gb "${MAX_CUDA_MEMORY_GB}" \
  --cuda-memory-check-interval "${CUDA_MEMORY_CHECK_INTERVAL}" \
  --allow-tf32 \
  --dataloader-num-workers "${DATALOADER_NUM_WORKERS}" \
  --dataloader-prefetch-factor "${DATALOADER_PREFETCH_FACTOR}" \
  --num-double-layers "${NUM_DOUBLE_LAYERS}" \
  --num-single-layers "${NUM_SINGLE_LAYERS}" \
  --guidance-scale "${GUIDANCE_SCALE}" \
  --report-to "${REPORT_TO}" \
  --tracker-project-name "${TRACKER_PROJECT_NAME}" \
  --cross-version v5
