"""Inference utilities for the unified Phase 5.4 edit pipeline."""

from .pipeline import (
    CrossV0InferenceBundle,
    EditPipelineInputs,
    EditPipelineResult,
    InpaintInferenceBundle,
    load_cross_bundle,
    load_inpaint_bundle,
    resolve_prompt,
    run_cross_v0_bundle,
    run_edit_pipeline,
    run_inpaint_bundle,
)
from .pipeline_cross_v2_1 import (
    CROSS_V2_1_REFERENCE_WITH_REF,
    CROSS_V2_1_REFERENCE_ZERO_REF,
    CrossV21InferenceBundle,
    compute_cross_v2_1_fixed_timestep_losses,
    load_cross_v2_1_bundle,
    run_cross_v2_1_bundle,
)
from .pipeline_cross_v3 import (
    CROSS_V3_PROMPT,
    CROSS_V3_REFERENCE_WITH_REF,
    CROSS_V3_REFERENCE_ZERO_REF,
    CrossV3InferenceBundle,
    compute_cross_v3_fixed_timestep_losses,
    load_cross_v3_bundle,
    run_cross_v3_bundle,
)
from .pipeline_cross_v4 import (
    CROSS_V4_PROMPT,
    CROSS_V4_REFERENCE_WITH_REF,
    CROSS_V4_REFERENCE_ZERO_REF,
    CrossV4InferenceBundle,
    load_cross_v4_bundle,
    run_cross_v4_bundle,
)
from .router import (
    EditRoutingConfig,
    EditRoutingDecision,
    compute_change_region_mask,
    route_edit_request,
)

__all__ = [
    "CrossV0InferenceBundle",
    "CrossV21InferenceBundle",
    "CrossV3InferenceBundle",
    "CrossV4InferenceBundle",
    "CROSS_V2_1_REFERENCE_WITH_REF",
    "CROSS_V2_1_REFERENCE_ZERO_REF",
    "CROSS_V3_PROMPT",
    "CROSS_V3_REFERENCE_WITH_REF",
    "CROSS_V3_REFERENCE_ZERO_REF",
    "CROSS_V4_PROMPT",
    "CROSS_V4_REFERENCE_WITH_REF",
    "CROSS_V4_REFERENCE_ZERO_REF",
    "EditPipelineInputs",
    "EditPipelineResult",
    "EditRoutingConfig",
    "EditRoutingDecision",
    "InpaintInferenceBundle",
    "compute_change_region_mask",
    "compute_cross_v2_1_fixed_timestep_losses",
    "compute_cross_v3_fixed_timestep_losses",
    "load_cross_bundle",
    "load_cross_v2_1_bundle",
    "load_cross_v3_bundle",
    "load_cross_v4_bundle",
    "load_inpaint_bundle",
    "resolve_prompt",
    "route_edit_request",
    "run_cross_v0_bundle",
    "run_cross_v2_1_bundle",
    "run_cross_v3_bundle",
    "run_cross_v4_bundle",
    "run_edit_pipeline",
    "run_inpaint_bundle",
]
