"""Inference utilities for the unified Phase 5.4 edit pipeline."""

from .pipeline import (
    EditPipelineInputs,
    EditPipelineResult,
    InpaintInferenceBundle,
    load_inpaint_bundle,
    resolve_prompt,
    run_edit_pipeline,
    run_inpaint_bundle,
)
from .model_paths import (
    DEFAULT_CROSS_V1_CHECKPOINT,
    DEFAULT_INPAINT_CHECKPOINT,
    DEFAULT_PIX2PIX_CHECKPOINT,
    DEFAULT_PROBNET_CHECKPOINT,
    FROZEN_PROBNET_SHA256,
    PRODUCTION_PIX2PIX_ENV,
    PRODUCTION_PIX2PIX_EPOCH,
    PRODUCTION_PIX2PIX_GLOBAL_STEP,
    PRODUCTION_PIX2PIX_SHA256,
    validate_frozen_probnet_checkpoint,
    validate_production_pix2pix_checkpoint,
)
from .router import (
    AgenticRouteFeatures,
    AgenticRoutingConfig,
    AgenticRoutingDecision,
    EditRoutingConfig,
    EditRoutingDecision,
    compute_agentic_route_features,
    compute_change_region_mask,
    route_agentic_edit_request,
    route_edit_request,
)
from .agentic import (
    PRODUCTION_CROSS_MODE,
    AgenticWorkflowConfig,
    AgenticWorkflowResult,
    FidelityThresholds,
    GenerationArtifact,
    RecoveryDecision,
    VerificationResult,
    default_recovery_policy,
    run_agentic_workflow,
    verify_mask_fidelity,
)

__all__ = [
    "AgenticRouteFeatures",
    "AgenticRoutingConfig",
    "AgenticRoutingDecision",
    "AgenticWorkflowConfig",
    "AgenticWorkflowResult",
    "DEFAULT_CROSS_V1_CHECKPOINT",
    "DEFAULT_INPAINT_CHECKPOINT",
    "DEFAULT_PIX2PIX_CHECKPOINT",
    "DEFAULT_PROBNET_CHECKPOINT",
    "FROZEN_PROBNET_SHA256",
    "PRODUCTION_PIX2PIX_ENV",
    "PRODUCTION_PIX2PIX_EPOCH",
    "PRODUCTION_PIX2PIX_GLOBAL_STEP",
    "PRODUCTION_PIX2PIX_SHA256",
    "EditPipelineInputs",
    "EditPipelineResult",
    "EditRoutingConfig",
    "EditRoutingDecision",
    "InpaintInferenceBundle",
    "FidelityThresholds",
    "GenerationArtifact",
    "PRODUCTION_CROSS_MODE",
    "RecoveryDecision",
    "VerificationResult",
    "compute_agentic_route_features",
    "compute_change_region_mask",
    "default_recovery_policy",
    "load_inpaint_bundle",
    "resolve_prompt",
    "route_agentic_edit_request",
    "route_edit_request",
    "run_agentic_workflow",
    "run_edit_pipeline",
    "run_inpaint_bundle",
    "validate_frozen_probnet_checkpoint",
    "validate_production_pix2pix_checkpoint",
    "verify_mask_fidelity",
]
